# config.yml

language: "en"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: RegexEntityExtractor
    use_lookup_tables: true
    use_regexes: true
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 300
  - name: FallbackClassifier
    threshold: 0.5
    ambiguity_threshold: 0.2
  - name: DucklingEntityExtractor
    dimensions: ["number"]

policies:
  - name: RulePolicy
    core_fallback_action_name: "utter_default_fallback"  # Sử dụng utter_* thay vì action_*
    core_fallback_threshold: 0.4
    max_predictions: 5  # Giới hạn số lần fallback
  - name: TEDPolicy
    max_history: 5
assistant_id: 20250513-215700-ragged-yard
